from .models import AppRoute, RoleName

DEFAULT_ROLES = [
    RoleName.super_admin,
    RoleName.platform_admin,
    RoleName.platform_user,
    RoleName.manager,
]

MANAGER_ROLES = [RoleName.super_admin, RoleName.platform_admin, RoleName.manager]

ROUTES: list[AppRoute] = [
    AppRoute(path="dashboard", roles=DEFAULT_ROLES, title="Dashboard"),
    AppRoute(path="live-streaming", roles=DEFAULT_ROLES, title="Live Streaming"),
    AppRoute(path="alertrecipients", roles=MANAGER_ROLES, title="Alert Recipients"),
    AppRoute(path="savedfiles", roles=DEFAULT_ROLES, title="Saved Files"),
    AppRoute(path="ladlehose", roles=DEFAULT_ROLES, title="Ladlehose"),
    AppRoute(path="plantview", roles=MANAGER_ROLES, title="Plant View"),
    AppRoute(path="plant", roles=MANAGER_ROLES, title="Plant Setup"),
    AppRoute(path="platformuser", roles=MANAGER_ROLES, title="Platform User"),
    AppRoute(path="recipientgroups", roles=MANAGER_ROLES, title="Recipient Groups"),
    AppRoute(path="preview-camera/:id", roles=DEFAULT_ROLES, title="Preview Camera", has_params=True),
    AppRoute(path="rule", roles=MANAGER_ROLES, title="Rules"),
    AppRoute(path="resetpwd", roles=MANAGER_ROLES, title="Reset Password"),
    AppRoute(path="camera", roles=MANAGER_ROLES, title="Camera"),
    AppRoute(path="zone", roles=MANAGER_ROLES, title="Zone"),
    AppRoute(path="wip", roles=DEFAULT_ROLES, title="WIP"),
    AppRoute(path="notification-description/:id", roles=DEFAULT_ROLES, title="Notification Description", has_params=True),
    AppRoute(path="streaming-alert-details/:id/:cameraId/:isFrom", roles=DEFAULT_ROLES, title="Streaming Alert Details", has_params=True),
    AppRoute(path="streaming-details/:id/:cameraId/:isFrom", roles=DEFAULT_ROLES, title="Streaming Details", has_params=True),
    AppRoute(path="preview-zone/:id", roles=DEFAULT_ROLES, title="Preview Zone", has_params=True),
    AppRoute(path="auth-dashboard", roles=DEFAULT_ROLES, title="Auth Dashboard"),
    AppRoute(path="vehicle-report", roles=DEFAULT_ROLES, title="Vehicle Report"),
    AppRoute(path="anamolies-report", roles=DEFAULT_ROLES, title="Anomalies Report"),
    AppRoute(path="usage-report", roles=MANAGER_ROLES, title="Usage Report"),
    AppRoute(path="ladlehose-report", roles=MANAGER_ROLES, title="Ladlehose Report"),
    AppRoute(path="attendance-report", roles=MANAGER_ROLES, title="Attendance Report"),
    AppRoute(path="mg-punch-in", roles=MANAGER_ROLES, title="Manager Punch In"),
    AppRoute(path="tg-punch-out", roles=MANAGER_ROLES, title="Target Punch Out"),
    AppRoute(path="department", roles=MANAGER_ROLES, title="Department"),
    AppRoute(path="analytics", roles=MANAGER_ROLES, title="Analytics"),
    AppRoute(path="all-notification", roles=DEFAULT_ROLES, title="All Notification"),
    AppRoute(path="camera-dashboard/:id", roles=DEFAULT_ROLES, title="Camera Dashboard", has_params=True),
    AppRoute(path="about", roles=DEFAULT_ROLES, title="About"),
    AppRoute(path="searchbyid", roles=DEFAULT_ROLES, title="Search by ID"),
    AppRoute(path="insights", roles=MANAGER_ROLES, title="Insights"),
    AppRoute(path="deep-insights", roles=MANAGER_ROLES, title="Deep Insights"),
    AppRoute(path="trend-charts", roles=MANAGER_ROLES, title="Trend Charts"),
    AppRoute(path="usage-metrics", roles=MANAGER_ROLES, title="Usage Metrics"),
    AppRoute(path="notification-management", roles=MANAGER_ROLES, title="Notification Management"),
    AppRoute(path="error-component", roles=DEFAULT_ROLES, title="Error Component"),
    AppRoute(path="my-ticket", roles=DEFAULT_ROLES, title="My Ticket"),
    AppRoute(path="user-preference", roles=DEFAULT_ROLES, title="User Preferences"),
    AppRoute(path="client", roles=DEFAULT_ROLES, title="Client"),
    AppRoute(path="unit", roles=DEFAULT_ROLES, title="Unit"),
    AppRoute(path="corporate-dashboard", roles=[RoleName.corporate], title="Corporate Dashboard"),
]
